#!/usr/bin/env python3
# Copyright (c) 2026, Marcin Kwiatkowski <marcin@kwiatkowski.info.pl>
# All rights reserved.

"""
Generate all codec-related files for the SIP stack.
Run from any directory; writes to /home/mkwiatkowski/Projects/SIP/
"""
import os

BASE = "/home/mkwiatkowski/Projects/SIP"

def W(rel, text):
    path = f"{BASE}/{rel}"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print(f"  {rel}  ({len(text)} bytes)")

print("Writing codec infrastructure...")

# ─────────────────────────────────────────────────────────────────────────────
# include/CodecPlugin.h
# ─────────────────────────────────────────────────────────────────────────────
W("include/CodecPlugin.h", r"""// CodecPlugin.h – Dynamically-attachable codec plugin system
//
// Three attachment methods (all produce ICodec* added to a CodecRegistry):
//
//  1. Compiled-in optional codecs (guarded by HAVE_xxx macros):
//       SLIN  – always available (raw PCM, zero deps)
//       GSM   – libgsm      (HAVE_GSM)
//       G729  – libbcg729   (HAVE_BCG729)
//       C2    – libcodec2   (HAVE_CODEC2)
//
//  2. Shared-library (.so) plugin – C ABI:
//       CodecPlugin::fromSo(path)   dlopen + 8 mandatory symbols
//       See "Plugin C ABI" below for how to write an external plugin.
//
//  3. C++ factory registration:
//       CodecPlugin::fromFactory(name, pt, clockRate, factory)
//       Useful when you have your own C++ ICodec subclass (G.723.1,
//       SILK, MELP, TWELP …) and want it auto-created on demand.
//
// Attach to a CodecRegistry via:
//   CodecPlugin p = CodecPlugin::fromSo("/usr/lib/mycodec.so");
//   if (p) registry.add(p.release());
//
// ── Plugin C ABI ──────────────────────────────────────────────────────────
//
// A shared library codec plugin must export ALL of these C symbols:
//
//   const char* sip_codec_name();          // e.g. "G729" "SILK" "MELP"
//   uint8_t     sip_codec_pt();            // RTP payload type (0..127)
//   uint32_t    sip_codec_clockrate();     // samples/second, e.g. 8000
//   uint8_t     sip_codec_channels();      // 1 (mono) or 2 (stereo)
//   size_t      sip_codec_frame_bytes();   // compressed bytes per frame
//   size_t      sip_codec_frame_samples(); // PCM samples per frame
//   void*       sip_codec_create();        // allocate codec state
//   void        sip_codec_destroy(void*);  // free codec state
//   size_t      sip_codec_encode(void* state,
//                                const int16_t* pcm, size_t samples,
//                                uint8_t* out, size_t outMax);
//   size_t      sip_codec_decode(void* state,
//                                const uint8_t* data, size_t len,
//                                int16_t* pcm, size_t maxSamples);
//
// Build the plugin as a shared library:
//   gcc -shared -fPIC -o mycodec.so mycodec.c -lmycodeclib
//
// A minimal plugin template is generated by:
//   sip_client --codec-template > mycodec_template.c
// ──────────────────────────────────────────────────────────────────────────
#pragma once
#include "Codec.h"
#include <functional>
#include <memory>

namespace sip {

// ── Plugin wrapper returned by factory functions ─────────────────────────────
// Behaves like unique_ptr<ICodec> with a boolean "valid" flag.
class CodecPlugin {
public:
    CodecPlugin() = default;
    explicit CodecPlugin(ICodec* c) : codec_(c) {}
    CodecPlugin(CodecPlugin&&) = default;
    CodecPlugin& operator=(CodecPlugin&&) = default;
    CodecPlugin(const CodecPlugin&) = delete;

    explicit operator bool() const { return codec_ != nullptr; }

    // Transfer ownership to caller (e.g. registry.add(p.release())).
    ICodec* release() { ICodec* c=codec_; codec_=nullptr; return c; }

    const char* name() const { return codec_ ? codec_->name() : "(null)"; }
    uint8_t     pt()   const { return codec_ ? codec_->payloadType() : 0; }

    // ── Builders ───────────────────────────────────────────────────────────

    // Load a .so plugin via dlopen.
    // Returns invalid CodecPlugin if the file is missing or ABI incomplete.
    static CodecPlugin fromSo(const char* soPath);

    // Register a C++ factory function.  The factory is called once now to
    // create the codec instance.  Use this when you have your own ICodec
    // subclass but don't want to write a shared library.
    //   Usage:
    //     auto p = CodecPlugin::fromFactory([]{ return new MySilkCodec(); });
    static CodecPlugin fromFactory(std::function<ICodec*()> factory);

    // ── Built-in optional codec builders ───────────────────────────────────

    // G.711 PCMU/PCMA (PT 0/8): always available, already in CodecRegistry
    // by default.  Listed for completeness.

    // SLIN – Signed 16-bit Linear PCM, 8 kHz, PT 11 (RFC 3551 "L16/8000/1")
    // No external dependency. Always compiled in.
    static CodecPlugin makeSlin(uint8_t pt = 11);

    // GSM Full-Rate (PT 3). Requires libgsm (-DHAVE_GSM).
    // Returns invalid plugin if not compiled with GSM support.
    static CodecPlugin makeGsm();

    // G.729A (PT 18). Requires libbcg729 (-DHAVE_BCG729).
    static CodecPlugin makeG729();

    // CODEC2 (default PT 96). Requires libcodec2 (-DHAVE_CODEC2).
    // mode: 0=3200bps 1=2400bps 2=1600bps 3=1400bps 4=1300bps 5=1200bps
    static CodecPlugin makeCodec2(int mode = 1, uint8_t pt = 96);

    // G.723.1 (PT 4). No OSS library available on this system.
    // Returns an invalid plugin unless a .so plugin provides it.
    // The stub below always returns silence on decode and silence on encode.
    // Replace by loading a real plugin: fromSo("/usr/lib/g7231codec.so")
    static CodecPlugin makeG7231Stub();

    // SILK (PT 97). No OSS library available on this system.
    // Stub only – replace via fromSo() or fromFactory().
    static CodecPlugin makeSilkStub(uint8_t pt = 97);

    // MELP 2400bps (PT 98). Stub – replace via fromSo() or fromFactory().
    static CodecPlugin makeMelpStub(uint8_t pt = 98);

    // MELPe (enhanced, 600/1200/2400bps) (PT 99). Stub.
    static CodecPlugin makeMelpeStub(uint8_t pt = 99);

    // TWELP (PT 100). Stub – no public open-source implementation known.
    // Attach your implementation via fromSo() or fromFactory().
    static CodecPlugin makeTwelpStub(uint8_t pt = 100);

private:
    ICodec* codec_ = nullptr;
};

// ── Convenience: register all available codecs into a registry ────────────────
// Adds: G711u, G711a, telephone-event (already in default registry),
//       SLIN, GSM (if HAVE_GSM), G.729 (if HAVE_BCG729),
//       CODEC2-2400 (if HAVE_CODEC2), and stubs for the rest.
// Dynamic PTs for stubs: C2=96 SILK=97 MELP=98 MELPe=99 TWELP=100
void registerAllCodecs(CodecRegistry& reg,
                       bool includeStubs = true);

// Print a plugin template to stdout (for writing new plugins).
void printCodecPluginTemplate();

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# include/codecs/SlinCodec.h
# ─────────────────────────────────────────────────────────────────────────────
W("include/codecs/SlinCodec.h", r"""// SlinCodec.h – Signed 16-bit Linear PCM (L16), 8 kHz mono
// RFC 3551 §4.5: payload type 11  (L16/8000/1)
// No external dependency.  Encode = memcpy (network byte order swap),
// Decode = memcpy (byte-swap back).  160 samples / 20 ms.
#pragma once
#include "Codec.h"
namespace sip {

class SlinCodec final : public ICodec {
public:
    explicit SlinCodec(uint8_t pt = 11) : pt_(pt) {}

    uint8_t     payloadType()  const override { return pt_; }
    const char* name()         const override { return "L16"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return 320; } // 160 * 2
    size_t      frameSamples() const override { return 160; }

    // Encode: host-endian int16 -> big-endian (network) int16
    size_t encode(const int16_t* pcm, size_t samples,
                  uint8_t* out, size_t outMax) override {
        size_t bytes = samples * 2;
        if (bytes > outMax) bytes = outMax & ~1u;
        for (size_t i = 0; i < bytes/2; ++i) {
            int16_t s = pcm[i];
            out[i*2  ] = (uint8_t)(s >> 8);
            out[i*2+1] = (uint8_t)(s);
        }
        return bytes;
    }

    // Decode: big-endian int16 -> host-endian int16
    size_t decode(const uint8_t* data, size_t len,
                  int16_t* pcm, size_t maxSamples) override {
        size_t samples = len / 2;
        if (samples > maxSamples) samples = maxSamples;
        for (size_t i = 0; i < samples; ++i)
            pcm[i] = (int16_t)((data[i*2] << 8) | data[i*2+1]);
        return samples;
    }

private:
    uint8_t pt_;
};

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# include/codecs/GsmCodec.h
# ─────────────────────────────────────────────────────────────────────────────
W("include/codecs/GsmCodec.h", r"""// GsmCodec.h – GSM Full-Rate (GSM-FR / GSM 06.10), PT 3
// Requires libgsm  (HAVE_GSM).  Frame: 160 samples in, 33 bytes out (20ms).
// libgsm API declared here manually to avoid requiring the -dev package.
#pragma once
#include "Codec.h"
#ifdef HAVE_GSM
extern "C" {
    typedef struct gsm_state *gsm;
    gsm    gsm_create(void);
    void   gsm_destroy(gsm);
    int    gsm_encode(gsm, short *src, unsigned char *dst);
    int    gsm_decode(gsm, unsigned char *src, short *dst);
}
#endif

namespace sip {

class GsmCodec final : public ICodec {
public:
    GsmCodec() {
#ifdef HAVE_GSM
        enc_ = gsm_create();
        dec_ = gsm_create();
#endif
    }
    ~GsmCodec() {
#ifdef HAVE_GSM
        if (enc_) gsm_destroy((gsm)enc_);
        if (dec_) gsm_destroy((gsm)dec_);
#endif
    }

    uint8_t     payloadType()  const override { return 3; }
    const char* name()         const override { return "GSM"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return 33; }
    size_t      frameSamples() const override { return 160; }

    size_t encode(const int16_t* pcm, size_t samples,
                  uint8_t* out, size_t outMax) override {
#ifdef HAVE_GSM
        if (!enc_ || samples < 160 || outMax < 33) return 0;
        gsm_encode((gsm)enc_, (short*)pcm, (unsigned char*)out);
        return 33;
#else
        (void)pcm; (void)samples; (void)out; (void)outMax; return 0;
#endif
    }
    size_t decode(const uint8_t* data, size_t len,
                  int16_t* pcm, size_t maxSamples) override {
#ifdef HAVE_GSM
        if (!dec_ || len < 33 || maxSamples < 160) return 0;
        if (gsm_decode((gsm)dec_, (unsigned char*)data, (short*)pcm) < 0) return 0;
        return 160;
#else
        (void)data; (void)len; (void)pcm; (void)maxSamples; return 0;
#endif
    }

    bool valid() const {
#ifdef HAVE_GSM
        return enc_ && dec_;
#else
        return false;
#endif
    }

private:
    void* enc_ = nullptr;
    void* dec_ = nullptr;
};

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# include/codecs/G729Codec.h
# ─────────────────────────────────────────────────────────────────────────────
W("include/codecs/G729Codec.h", r"""// G729Codec.h – G.729A (Annex A, 8kbps), PT 18
// Requires libbcg729  (HAVE_BCG729).
// bcg729 API declared here manually (no -dev header installed).
// Frame: 80 samples / 10ms → 10 bytes.  Two 10ms frames pack into 20ms.
// RTP carries 20 bytes per 20ms packet (two concatenated 10ms frames).
#pragma once
#include "Codec.h"
#ifdef HAVE_BCG729
extern "C" {
    // bcg729 opaque handles
    typedef void* Bcg729EncoderChannelContextStruct;
    typedef void* Bcg729DecoderChannelContextStruct;
    Bcg729EncoderChannelContextStruct* initBcg729EncoderChannel(void);
    Bcg729DecoderChannelContextStruct* initBcg729DecoderChannel(void);
    void closeBcg729EncoderChannel(Bcg729EncoderChannelContextStruct*);
    void closeBcg729DecoderChannel(Bcg729DecoderChannelContextStruct*);
    // Encode 80 int16 PCM samples -> 10 bytes. SIDFlag set if comfort noise.
    void bcg729Encoder(Bcg729EncoderChannelContextStruct*,
                       short* inputFrame, unsigned char* bitStream,
                       unsigned char* SIDFlag);
    // Decode 10 bytes -> 80 int16 PCM samples.
    void bcg729Decoder(Bcg729DecoderChannelContextStruct*,
                       unsigned char* bitStream, signed char sizeOfFrame,
                       short* signal, unsigned char erasureFlag,
                       unsigned char SIDFrameFlag, unsigned char rfc3389PayloadFlag);
}
#endif

namespace sip {

class G729Codec final : public ICodec {
public:
    G729Codec() {
#ifdef HAVE_BCG729
        enc_ = initBcg729EncoderChannel();
        dec_ = initBcg729DecoderChannel();
#endif
    }
    ~G729Codec() {
#ifdef HAVE_BCG729
        if (enc_) closeBcg729EncoderChannel(enc_);
        if (dec_) closeBcg729DecoderChannel(dec_);
#endif
    }

    uint8_t     payloadType()  const override { return 18; }
    const char* name()         const override { return "G729"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    // 20ms frame = two 10ms sub-frames = 20 bytes
    size_t      frameBytes()   const override { return 20; }
    size_t      frameSamples() const override { return 160; }

    // Encode 160 samples (20ms) → 20 bytes (two 10-byte G.729 frames)
    size_t encode(const int16_t* pcm, size_t samples,
                  uint8_t* out, size_t outMax) override {
#ifdef HAVE_BCG729
        if (!enc_ || samples < 160 || outMax < 20) return 0;
        unsigned char sid = 0;
        bcg729Encoder(enc_, (short*)pcm,       out,    &sid);
        bcg729Encoder(enc_, (short*)(pcm+80),  out+10, &sid);
        return 20;
#else
        (void)pcm;(void)samples;(void)out;(void)outMax; return 0;
#endif
    }

    // Decode 10 or 20 bytes → 80 or 160 samples
    size_t decode(const uint8_t* data, size_t len,
                  int16_t* pcm, size_t maxSamples) override {
#ifdef HAVE_BCG729
        if (!dec_ || maxSamples < 80) return 0;
        size_t out = 0;
        if (len >= 10) {
            bcg729Decoder(dec_, (unsigned char*)data,   10, (short*)pcm,     0, 0, 0);
            out = 80;
        }
        if (len >= 20 && maxSamples >= 160) {
            bcg729Decoder(dec_, (unsigned char*)data+10,10, (short*)(pcm+80),0, 0, 0);
            out = 160;
        }
        return out;
#else
        (void)data;(void)len;(void)pcm;(void)maxSamples; return 0;
#endif
    }

    bool valid() const {
#ifdef HAVE_BCG729
        return enc_ && dec_;
#else
        return false;
#endif
    }

private:
#ifdef HAVE_BCG729
    Bcg729EncoderChannelContextStruct* enc_ = nullptr;
    Bcg729DecoderChannelContextStruct* dec_ = nullptr;
#else
    void* enc_ = nullptr;
    void* dec_ = nullptr;
#endif
};

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# include/codecs/Codec2Codec.h
# ─────────────────────────────────────────────────────────────────────────────
W("include/codecs/Codec2Codec.h", r"""// Codec2Codec.h – CODEC2 (David Rowe, open-source), dynamic PT
// Requires libcodec2  (HAVE_CODEC2).
// Modes: 0=3200 1=2400 2=1600 3=1400 4=1300 5=1200 bps
//   3200/2400: 160 samples/frame (20ms)
//   1600/1400/1300/1200: 320 samples/frame (40ms)
// libcodec2 API declared manually (no -dev header required).
#pragma once
#include "Codec.h"
#ifdef HAVE_CODEC2
extern "C" {
    struct CODEC2; // opaque
    struct CODEC2* codec2_create(int mode);
    void           codec2_destroy(struct CODEC2*);
    void           codec2_encode(struct CODEC2*, unsigned char* bits, short* speech_in);
    void           codec2_decode(struct CODEC2*, short* speech_out, const unsigned char* bits);
    int            codec2_samples_per_frame(struct CODEC2*);
    int            codec2_bits_per_frame(struct CODEC2*);
}
#endif

namespace sip {

// CODEC2 mode constants (from codec2.h)
enum class Codec2Mode : int {
    BPS_3200 = 0,
    BPS_2400 = 1,
    BPS_1600 = 2,
    BPS_1400 = 3,
    BPS_1300 = 4,
    BPS_1200 = 5,
};

class Codec2Codec final : public ICodec {
public:
    // pt: dynamic, default 96.  mode: Codec2Mode enum.
    Codec2Codec(Codec2Mode mode = Codec2Mode::BPS_2400, uint8_t pt = 96)
        : mode_(mode), pt_(pt) {
#ifdef HAVE_CODEC2
        ctx_ = codec2_create((int)mode);
        if (ctx_) {
            sampPerFrame_ = (size_t)codec2_samples_per_frame(ctx_);
            bitsPerFrame_ = (size_t)codec2_bits_per_frame(ctx_);
            bytesPerFrame_= (bitsPerFrame_ + 7) / 8;
        }
#endif
    }
    ~Codec2Codec() {
#ifdef HAVE_CODEC2
        if (ctx_) codec2_destroy(ctx_);
#endif
    }

    uint8_t     payloadType()  const override { return pt_; }
    const char* name()         const override { return "CODEC2"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return bytesPerFrame_; }
    size_t      frameSamples() const override { return sampPerFrame_; }

    size_t encode(const int16_t* pcm, size_t samples,
                  uint8_t* out, size_t outMax) override {
#ifdef HAVE_CODEC2
        if (!ctx_ || samples < sampPerFrame_ || outMax < bytesPerFrame_) return 0;
        codec2_encode(ctx_, out, (short*)pcm);
        return bytesPerFrame_;
#else
        (void)pcm;(void)samples;(void)out;(void)outMax; return 0;
#endif
    }
    size_t decode(const uint8_t* data, size_t len,
                  int16_t* pcm, size_t maxSamples) override {
#ifdef HAVE_CODEC2
        if (!ctx_ || len < bytesPerFrame_ || maxSamples < sampPerFrame_) return 0;
        codec2_decode(ctx_, (short*)pcm, data);
        return sampPerFrame_;
#else
        (void)data;(void)len;(void)pcm;(void)maxSamples; return 0;
#endif
    }

    bool        valid() const { return ctx_ != nullptr; }
    Codec2Mode  mode()  const { return mode_; }
    size_t      bitsPerFrame() const { return bitsPerFrame_; }

private:
    Codec2Mode  mode_;
    uint8_t     pt_;
#ifdef HAVE_CODEC2
    struct CODEC2* ctx_ = nullptr;
#else
    void* ctx_ = nullptr;
#endif
    size_t sampPerFrame_  = 160;
    size_t bitsPerFrame_  = 48;
    size_t bytesPerFrame_ = 6;
};

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# include/codecs/StubCodec.h  – template for unavailable codecs
# ─────────────────────────────────────────────────────────────────────────────
W("include/codecs/StubCodec.h", r"""// StubCodec.h – Placeholder ICodec for codecs with no OSS implementation.
//
// A StubCodec:
//   - Registers correctly in CodecRegistry so SDP offer/answer includes
//     the codec in the capability list.
//   - encode() always returns 0 (silence).
//   - decode() always returns silence frames (zeros).
//   - valid() returns false.
//
// Replace a stub by calling CodecRegistry::replace(pt, realCodec) after
// loading the real implementation via CodecPlugin::fromSo() or fromFactory().
//
// Codecs implemented as stubs here:
//   G.723.1  – PT  4 –  6.3/5.3 kbps, 30ms frames
//   SILK     – PT 97 –  variable bitrate 6–40 kbps  (Skype / RFC 7587)
//   MELP     – PT 98 –  2400 bps, 22.5ms frames (MIL-STD-3005/STANAG 4591)
//   MELPe    – PT 99 –  600/1200/2400 bps          (STANAG 4591)
//   TWELP    – PT 100–  600 bps (Wideband LPC, NATO STANAG 4198 family)
//
// Real open-source / commercial implementations:
//   G.723.1 : Intel IPP, bcg7231 (not publicly available)
//             Or load an Asterisk-compatible .so plugin
//   SILK    : https://github.com/gaozehua/SILKCodec (original Skype SDK)
//             Or use libopus which subsumes SILK via Opus hybrid mode
//   MELP    : US DoD reference code (MELP_STANAG4591.zip from DISA)
//             Or commercial impl from Vocal Technologies / DVSI
//   MELPe   : Same sources as MELP above
//   TWELP   : SPAWAR / NATO reference implementation
//             Or commercial impl; contact codec vendor
#pragma once
#include "Codec.h"
#include <cstring>
namespace sip {

class StubCodec final : public ICodec {
public:
    StubCodec(const char* name, uint8_t pt, uint32_t clockRate,
              size_t frameBytes, size_t frameSamples)
        : pt_(pt), clockRate_(clockRate),
          frameBytes_(frameBytes), frameSamples_(frameSamples) {
        // copy name safely
        size_t l = strlen(name); if(l>=sizeof(name_)-1) l=sizeof(name_)-1;
        memcpy(name_, name, l); name_[l]=0;
    }

    uint8_t     payloadType()  const override { return pt_; }
    const char* name()         const override { return name_; }
    uint32_t    clockRate()    const override { return clockRate_; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return frameBytes_; }
    size_t      frameSamples() const override { return frameSamples_; }

    size_t encode(const int16_t*, size_t, uint8_t*, size_t) override { return 0; }
    size_t decode(const uint8_t*, size_t,
                  int16_t* pcm, size_t maxSamples) override {
        // Comfort noise (silence) so the call doesn't crash
        size_t n = (maxSamples < frameSamples_) ? maxSamples : frameSamples_;
        memset(pcm, 0, n * 2);
        return n;
    }
    bool valid() const { return false; }

private:
    char     name_[32]   = {};
    uint8_t  pt_;
    uint32_t clockRate_;
    size_t   frameBytes_;
    size_t   frameSamples_;
};

// ── Pre-configured stubs ──────────────────────────────────────────────────────

// G.723.1 – 30ms / 240 samples per frame; 6.3kbps → 24 bytes, 5.3kbps → 20 bytes
// We announce 6.3kbps (24 bytes) in SDP.
inline StubCodec* makeG7231Stub() {
    return new StubCodec("G7231", 4, 8000, 24, 240);
}

// SILK wideband – 20ms frames at 16kHz (320 samples), variable bytes.
// Fallback announcement: 20ms @ 8kHz (160 samples), 32 bytes (12.8kbps).
inline StubCodec* makeSilkStub(uint8_t pt = 97) {
    return new StubCodec("SILK", pt, 8000, 32, 160);
}

// MELP 2400 bps – 22.5ms/180 samples per frame, 54 bits = 7 bytes (padded to 8)
inline StubCodec* makeMelpStub(uint8_t pt = 98) {
    return new StubCodec("MELP", pt, 8000, 8, 180);
}

// MELPe – same frame structure, announced at 2400bps default
inline StubCodec* makeMelpeStub(uint8_t pt = 99) {
    return new StubCodec("MELPe", pt, 8000, 8, 180);
}

// TWELP (Wideband LPC ~600bps variant, 30ms frames)
inline StubCodec* makeTwelpStub(uint8_t pt = 100) {
    return new StubCodec("TWELP", pt, 8000, 4, 240);
}

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# src/CodecPlugin.cpp
# ─────────────────────────────────────────────────────────────────────────────
W("src/CodecPlugin.cpp", r"""// CodecPlugin.cpp – Dynamic codec attachment (dlopen + factory)
#include "CodecPlugin.h"
#include "codecs/SlinCodec.h"
#include "codecs/GsmCodec.h"
#include "codecs/G729Codec.h"
#include "codecs/Codec2Codec.h"
#include "codecs/StubCodec.h"
#include <cstdio>
#include <cstring>
#include <dlfcn.h>

namespace sip {

// ── C ABI shim wrapping a dlopen'd .so codec ─────────────────────────────────
class SoCodec final : public ICodec {
public:
    using FnName    = const char*(*)();
    using FnPt      = uint8_t(*)();
    using FnClk     = uint32_t(*)();
    using FnCh      = uint8_t(*)();
    using FnSzB     = size_t(*)();
    using FnCreate  = void*(*)();
    using FnDestroy = void(*)(void*);
    using FnEncode  = size_t(*)(void*, const int16_t*, size_t, uint8_t*, size_t);
    using FnDecode  = size_t(*)(void*, const uint8_t*, size_t, int16_t*, size_t);

    void*     dl      = nullptr;
    void*     state   = nullptr;
    FnName    fnName  = nullptr;
    FnPt      fnPt    = nullptr;
    FnClk     fnClk   = nullptr;
    FnCh      fnCh    = nullptr;
    FnSzB     fnFrB   = nullptr;
    FnSzB     fnFrS   = nullptr;
    FnDestroy fnDest  = nullptr;
    FnEncode  fnEnc   = nullptr;
    FnDecode  fnDec   = nullptr;

    ~SoCodec() {
        if (state && fnDest) fnDest(state);
        if (dl) dlclose(dl);
    }

    uint8_t     payloadType()  const override { return fnPt  ? fnPt()  : 0;   }
    const char* name()         const override { return fnName? fnName(): "?";  }
    uint32_t    clockRate()    const override { return fnClk ? fnClk() : 8000; }
    uint8_t     channels()     const override { return fnCh  ? fnCh()  : 1;   }
    size_t      frameBytes()   const override { return fnFrB ? fnFrB() : 0;   }
    size_t      frameSamples() const override { return fnFrS ? fnFrS() : 160; }

    size_t encode(const int16_t* pcm, size_t n, uint8_t* out, size_t max) override {
        return (fnEnc && state) ? fnEnc(state, pcm, n, out, max) : 0;
    }
    size_t decode(const uint8_t* in, size_t n, int16_t* pcm, size_t max) override {
        return (fnDec && state) ? fnDec(state, in, n, pcm, max) : 0;
    }
};

// ── CodecPlugin::fromSo ───────────────────────────────────────────────────────
CodecPlugin CodecPlugin::fromSo(const char* soPath) {
    void* dl = dlopen(soPath, RTLD_NOW | RTLD_LOCAL);
    if (!dl) {
        fprintf(stderr, "[CODEC] dlopen(%s): %s\n", soPath, dlerror());
        return CodecPlugin();
    }
#define LOAD(sym, field, type) \
    sc->field = (SoCodec::type)dlsym(dl, sym); \
    if (!sc->field) { fprintf(stderr,"[CODEC] missing symbol '%s' in %s\n", sym, soPath); \
                      dlclose(dl); delete sc; return CodecPlugin(); }

    auto* sc = new SoCodec();
    sc->dl = dl;
    LOAD("sip_codec_name",          fnName, FnName)
    LOAD("sip_codec_pt",            fnPt,   FnPt)
    LOAD("sip_codec_clockrate",     fnClk,  FnClk)
    LOAD("sip_codec_channels",      fnCh,   FnCh)
    LOAD("sip_codec_frame_bytes",   fnFrB,  FnSzB)
    LOAD("sip_codec_frame_samples", fnFrS,  FnSzB)
    LOAD("sip_codec_destroy",       fnDest, FnDestroy)
    LOAD("sip_codec_encode",        fnEnc,  FnEncode)
    LOAD("sip_codec_decode",        fnDec,  FnDecode)
#undef LOAD
    // sip_codec_create is optional (some stateless codecs skip it)
    auto fnCreate = (SoCodec::FnCreate)dlsym(dl, "sip_codec_create");
    if (fnCreate) sc->state = fnCreate();
    printf("[CODEC] Loaded plugin %s  PT=%u  %s\n",
           soPath, sc->fnPt(), sc->fnName());
    return CodecPlugin(sc);
}

// ── CodecPlugin::fromFactory ─────────────────────────────────────────────────
CodecPlugin CodecPlugin::fromFactory(std::function<ICodec*()> factory) {
    ICodec* c = factory();
    if (!c) return CodecPlugin();
    printf("[CODEC] Factory-registered codec %s  PT=%u\n", c->name(), c->payloadType());
    return CodecPlugin(c);
}

// ── Built-in codec builders ───────────────────────────────────────────────────
CodecPlugin CodecPlugin::makeSlin(uint8_t pt)     { return CodecPlugin(new SlinCodec(pt)); }
CodecPlugin CodecPlugin::makeGsm()                { auto* c=new GsmCodec(); return c->valid()?CodecPlugin(c):(delete c,CodecPlugin()); }
CodecPlugin CodecPlugin::makeG729()               { auto* c=new G729Codec(); return c->valid()?CodecPlugin(c):(delete c,CodecPlugin()); }
CodecPlugin CodecPlugin::makeCodec2(int m, uint8_t pt){ auto*c=new Codec2Codec((Codec2Mode)m,pt); return c->valid()?CodecPlugin(c):(delete c,CodecPlugin()); }
CodecPlugin CodecPlugin::makeG7231Stub()          { return CodecPlugin(makeG7231Stub());   }
CodecPlugin CodecPlugin::makeSilkStub(uint8_t pt) { return CodecPlugin(sip::makeSilkStub(pt)); }
CodecPlugin CodecPlugin::makeMelpStub(uint8_t pt) { return CodecPlugin(sip::makeMelpStub(pt)); }
CodecPlugin CodecPlugin::makeMelpeStub(uint8_t pt){ return CodecPlugin(sip::makeMelpeStub(pt));}
CodecPlugin CodecPlugin::makeTwelpStub(uint8_t pt){ return CodecPlugin(sip::makeTwelpStub(pt));}

// ── registerAllCodecs ─────────────────────────────────────────────────────────
void registerAllCodecs(CodecRegistry& reg, bool includeStubs) {
    // G.711 u-law/a-law + telephone-event already in default CodecRegistry ctor.

    // SLIN (L16 8kHz mono, PT 11) – always available
    { auto p=CodecPlugin::makeSlin(); if(p) reg.add(p.release()); }

    // GSM FR (PT 3)
    { auto p=CodecPlugin::makeGsm();
      if(p) { reg.add(p.release()); printf("[CODEC] GSM-FR loaded\n"); }
      else    printf("[CODEC] GSM-FR: HAVE_GSM not set or libgsm missing\n"); }

    // G.729A (PT 18)
    { auto p=CodecPlugin::makeG729();
      if(p) { reg.add(p.release()); printf("[CODEC] G.729A loaded\n"); }
      else    printf("[CODEC] G.729A: HAVE_BCG729 not set or libbcg729 missing\n"); }

    // CODEC2 2400bps (PT 96)
    { auto p=CodecPlugin::makeCodec2(1, 96);
      if(p) { reg.add(p.release()); printf("[CODEC] CODEC2-2400 loaded\n"); }
      else    printf("[CODEC] CODEC2: HAVE_CODEC2 not set or libcodec2 missing\n"); }

    if (!includeStubs) return;

    // Stubs for codecs with no OSS library
    { auto p=CodecPlugin::makeG7231Stub();  if(p) reg.add(p.release()); }
    { auto p=CodecPlugin::makeSilkStub();   if(p) reg.add(p.release()); }
    { auto p=CodecPlugin::makeMelpStub();   if(p) reg.add(p.release()); }
    { auto p=CodecPlugin::makeMelpeStub();  if(p) reg.add(p.release()); }
    { auto p=CodecPlugin::makeTwelpStub();  if(p) reg.add(p.release()); }

    printf("[CODEC] Stubs registered: G.723.1(PT4) SILK(PT97) MELP(PT98) MELPe(PT99) TWELP(PT100)\n");
    printf("[CODEC] Replace stubs via CodecPlugin::fromSo() or fromFactory()\n");
}

// ── Plugin template ───────────────────────────────────────────────────────────
void printCodecPluginTemplate() {
    puts(
R"(/* ── SIP stack codec plugin template ──────────────────────────────────────
 * Compile:  gcc -shared -fPIC -o mycodec.so mycodec.c -lmycodeclib
 * Load:     CodecPlugin p = CodecPlugin::fromSo("./mycodec.so");
 *           if (p) registry.add(p.release());
 * -------------------------------------------------------------------------*/
#include <stdint.h>
#include <stddef.h>
#include <string.h>

/* Replace these with your codec's real implementation */
#define MY_CODEC_NAME       "MYCODEC"
#define MY_CODEC_PT         97          /* dynamic PT 96–127 */
#define MY_CODEC_CLOCKRATE  8000
#define MY_CODEC_CHANNELS   1
#define MY_CODEC_FRAME_BYTES  20        /* compressed bytes per frame */
#define MY_CODEC_FRAME_SAMPLES 160      /* PCM samples per frame (20ms@8kHz) */

typedef struct { /* your codec state */ int dummy; } MyCodecState;

const char* sip_codec_name()          { return MY_CODEC_NAME; }
uint8_t     sip_codec_pt()            { return MY_CODEC_PT; }
uint32_t    sip_codec_clockrate()     { return MY_CODEC_CLOCKRATE; }
uint8_t     sip_codec_channels()      { return MY_CODEC_CHANNELS; }
size_t      sip_codec_frame_bytes()   { return MY_CODEC_FRAME_BYTES; }
size_t      sip_codec_frame_samples() { return MY_CODEC_FRAME_SAMPLES; }

void* sip_codec_create() {
    MyCodecState* s = calloc(1, sizeof(MyCodecState));
    /* your_codec_init(s); */
    return s;
}
void sip_codec_destroy(void* state) {
    /* your_codec_free((MyCodecState*)state); */
    free(state);
}
size_t sip_codec_encode(void* state,
                        const int16_t* pcm, size_t samples,
                        uint8_t* out, size_t outMax) {
    if (samples < MY_CODEC_FRAME_SAMPLES || outMax < MY_CODEC_FRAME_BYTES) return 0;
    /* your_codec_encode((MyCodecState*)state, pcm, out); */
    memset(out, 0, MY_CODEC_FRAME_BYTES); /* placeholder */
    return MY_CODEC_FRAME_BYTES;
}
size_t sip_codec_decode(void* state,
                        const uint8_t* data, size_t len,
                        int16_t* pcm, size_t maxSamples) {
    if (len < MY_CODEC_FRAME_BYTES || maxSamples < MY_CODEC_FRAME_SAMPLES) return 0;
    /* your_codec_decode((MyCodecState*)state, data, pcm); */
    memset(pcm, 0, MY_CODEC_FRAME_SAMPLES * 2); /* placeholder */
    return MY_CODEC_FRAME_SAMPLES;
}
)");
}

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# Update Codec.h – add replace() to CodecRegistry
# ─────────────────────────────────────────────────────────────────────────────
W("include/Codec.h", r"""// Codec.h – Audio codec interface + G.711 + CodecRegistry
// Extended with replace() for stub replacement and findByName().
#pragma once
#include <cstdint>
#include <cstddef>

namespace sip {

// ── Abstract codec interface ──────────────────────────────────────────────────
class ICodec {
public:
    virtual ~ICodec() = default;
    virtual uint8_t     payloadType()  const = 0;
    virtual const char* name()         const = 0;
    virtual uint32_t    clockRate()    const = 0;
    virtual uint8_t     channels()     const = 0;
    // Compressed bytes per single frame (encode input / decode output)
    virtual size_t      frameBytes()   const = 0;
    // PCM samples per single frame (encode input / decode output)
    virtual size_t      frameSamples() const = 0;
    // Returns compressed bytes written (0 = error/unsupported)
    virtual size_t encode(const int16_t* pcm, size_t samples,
                          uint8_t* out, size_t outMax) = 0;
    // Returns PCM samples decoded (0 = error/unsupported)
    virtual size_t decode(const uint8_t* data, size_t len,
                          int16_t* pcm, size_t maxSamples) = 0;
};

// ── G.711 μ-law (PCMU, PT 0, 8 kHz) ─────────────────────────────────────────
class G711u final : public ICodec {
public:
    uint8_t     payloadType()  const override { return 0; }
    const char* name()         const override { return "PCMU"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return 160; }
    size_t      frameSamples() const override { return 160; }
    size_t encode(const int16_t*, size_t, uint8_t*, size_t) override;
    size_t decode(const uint8_t*, size_t, int16_t*, size_t) override;
    static uint8_t  encodeSample(int16_t linear);
    static int16_t  decodeSample(uint8_t ulaw);
};

// ── G.711 A-law (PCMA, PT 8, 8 kHz) ─────────────────────────────────────────
class G711a final : public ICodec {
public:
    uint8_t     payloadType()  const override { return 8; }
    const char* name()         const override { return "PCMA"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return 160; }
    size_t      frameSamples() const override { return 160; }
    size_t encode(const int16_t*, size_t, uint8_t*, size_t) override;
    size_t decode(const uint8_t*, size_t, int16_t*, size_t) override;
    static uint8_t  encodeSample(int16_t linear);
    static int16_t  decodeSample(uint8_t alaw);
};

// ── Telephone-event (RFC 4733, PT 101) ────────────────────────────────────────
class TelephoneEvent final : public ICodec {
public:
    uint8_t     payloadType()  const override { return 101; }
    const char* name()         const override { return "telephone-event"; }
    uint32_t    clockRate()    const override { return 8000; }
    uint8_t     channels()     const override { return 1; }
    size_t      frameBytes()   const override { return 4; }
    size_t      frameSamples() const override { return 160; }
    size_t encode(const int16_t*, size_t, uint8_t*, size_t) override { return 0; }
    size_t decode(const uint8_t*, size_t, int16_t*, size_t) override { return 0; }
};

// ── Codec registry ────────────────────────────────────────────────────────────
class CodecRegistry {
public:
    static constexpr size_t Cap = 32;   // increased from 16 for extended codec set

    // Default constructor registers G711u, G711a, TelephoneEvent.
    CodecRegistry();
    ~CodecRegistry();

    // Add a codec. Ownership is transferred; registry will delete on destruction.
    // Returns false if registry is full or PT already registered.
    bool add(ICodec* c);

    // Replace an existing codec by payload type.
    // Old codec is deleted; new codec takes its slot.
    // Returns false if PT not found.
    bool replace(uint8_t pt, ICodec* newCodec);

    // Remove a codec by payload type. Returns false if not found.
    bool remove(uint8_t pt);

    ICodec* findByPT(uint8_t pt)     const;
    ICodec* findByName(const char* n) const;
    ICodec* at(size_t i)             const { return i<count_?codecs_[i]:nullptr; }
    size_t  count()                  const { return count_; }

    // Print registered codecs to stdout.
    void printAll() const;

private:
    ICodec* codecs_[Cap] = {};
    bool    owned_[Cap]  = {};   // true if registry should delete
    size_t  count_       = 0;

    G711u          g711u_;
    G711a          g711a_;
    TelephoneEvent telEv_;
};

} // namespace sip
""")

# ─────────────────────────────────────────────────────────────────────────────
# src/Codec.cpp – updated with replace() / remove() / printAll()
# ─────────────────────────────────────────────────────────────────────────────
W("src/Codec.cpp", r"""// Codec.cpp – G.711 implementation + CodecRegistry
#include "Codec.h"
#include <cstdio>
#include <cstring>
#include <cctype>

namespace sip {

// ── G.711 μ-law ──────────────────────────────────────────────────────────────
static const int16_t kUlawDecodeTable[256] = {
    -32124,-31100,-30076,-29052,-28028,-27004,-25980,-24956,
    -23932,-22908,-21884,-20860,-19836,-18812,-17788,-16764,
    -15996,-15484,-14972,-14460,-13948,-13436,-12924,-12412,
    -11900,-11388,-10876,-10364, -9852, -9340, -8828, -8316,
     -7932, -7676, -7420, -7164, -6908, -6652, -6396, -6140,
     -5884, -5628, -5372, -5116, -4860, -4604, -4348, -4092,
     -3900, -3772, -3644, -3516, -3388, -3260, -3132, -3004,
     -2876, -2748, -2620, -2492, -2364, -2236, -2108, -1980,
     -1884, -1820, -1756, -1692, -1628, -1564, -1500, -1436,
     -1372, -1308, -1244, -1180, -1116, -1052,  -988,  -924,
      -876,  -844,  -812,  -780,  -748,  -716,  -684,  -652,
      -620,  -588,  -556,  -524,  -492,  -460,  -428,  -396,
      -372,  -356,  -340,  -324,  -308,  -292,  -276,  -260,
      -244,  -228,  -212,  -196,  -180,  -164,  -148,  -132,
      -120,  -112,  -104,   -96,   -88,   -80,   -72,   -64,
       -56,   -48,   -40,   -32,   -24,   -16,    -8,     0,
     32124, 31100, 30076, 29052, 28028, 27004, 25980, 24956,
     23932, 22908, 21884, 20860, 19836, 18812, 17788, 16764,
     15996, 15484, 14972, 14460, 13948, 13436, 12924, 12412,
     11900, 11388, 10876, 10364,  9852,  9340,  8828,  8316,
      7932,  7676,  7420,  7164,  6908,  6652,  6396,  6140,
      5884,  5628,  5372,  5116,  4860,  4604,  4348,  4092,
      3900,  3772,  3644,  3516,  3388,  3260,  3132,  3004,
      2876,  2748,  2620,  2492,  2364,  2236,  2108,  1980,
      1884,  1820,  1756,  1692,  1628,  1564,  1500,  1436,
      1372,  1308,  1244,  1180,  1116,  1052,   988,   924,
       876,   844,   812,   780,   748,   716,   684,   652,
       620,   588,   556,   524,   492,   460,   428,   396,
       372,   356,   340,   324,   308,   292,   276,   260,
       244,   228,   212,   196,   180,   164,   148,   132,
       120,   112,   104,    96,    88,    80,    72,    64,
        56,    48,    40,    32,    24,    16,     8,     0
};

uint8_t G711u::encodeSample(int16_t s) {
    int sign = (s < 0) ? 0 : 0x80;
    if (s < 0) s = -s;
    if (s > 32635) s = 32635;
    s += 132;
    int exp = 7;
    for (int mask = 0x4000; !(s & mask); --exp, mask >>= 1) {}
    int mant = (s >> (exp + 3)) & 0x0F;
    return (uint8_t)(~(sign | (exp << 4) | mant));
}
int16_t G711u::decodeSample(uint8_t u) { return kUlawDecodeTable[u]; }
size_t G711u::encode(const int16_t* pcm, size_t n, uint8_t* out, size_t max) {
    if (n > max) n = max;
    for (size_t i=0;i<n;++i) out[i]=encodeSample(pcm[i]);
    return n;
}
size_t G711u::decode(const uint8_t* in, size_t n, int16_t* pcm, size_t max) {
    if (n > max) n = max;
    for (size_t i=0;i<n;++i) pcm[i]=decodeSample(in[i]);
    return n;
}

// ── G.711 A-law ──────────────────────────────────────────────────────────────
uint8_t G711a::encodeSample(int16_t s) {
    int sign = (s >= 0) ? 0x80 : 0;
    if (s < 0) s = ~s;
    if (s > 32767) s = 32767;
    uint8_t exp = 7;
    for (int mask = 0x4000; !(s & mask) && exp > 0; --exp, mask>>=1){}
    uint8_t mant;
    if (exp == 0) mant = (uint8_t)(s >> 1) & 0x0F;
    else          mant = (uint8_t)(s >> (exp)) & 0x0F;
    return (uint8_t)((sign | (exp<<4) | mant) ^ 0x55);
}
int16_t G711a::decodeSample(uint8_t a) {
    a ^= 0x55;
    int sign = a & 0x80;
    int exp  = (a >> 4) & 0x07;
    int mant = a & 0x0F;
    int s = (exp == 0) ? (mant << 1) | 1 : ((mant | 0x10) << exp);
    s <<= 3;
    return (int16_t)(sign ? s : -s);
}
size_t G711a::encode(const int16_t* pcm, size_t n, uint8_t* out, size_t max) {
    if (n > max) n = max;
    for (size_t i=0;i<n;++i) out[i]=encodeSample(pcm[i]);
    return n;
}
size_t G711a::decode(const uint8_t* in, size_t n, int16_t* pcm, size_t max) {
    if (n > max) n = max;
    for (size_t i=0;i<n;++i) pcm[i]=decodeSample(in[i]);
    return n;
}

// ── CodecRegistry ─────────────────────────────────────────────────────────────
CodecRegistry::CodecRegistry() {
    // Built-in non-owned codecs
    codecs_[0]=&g711u_; owned_[0]=false;
    codecs_[1]=&g711a_; owned_[1]=false;
    codecs_[2]=&telEv_; owned_[2]=false;
    count_=3;
}
CodecRegistry::~CodecRegistry() {
    for (size_t i=0;i<count_;++i) if (owned_[i]) delete codecs_[i];
}

bool CodecRegistry::add(ICodec* c) {
    if (!c || count_ >= Cap) return false;
    for (size_t i=0;i<count_;++i)
        if (codecs_[i]->payloadType()==c->payloadType()) return false; // duplicate PT
    codecs_[count_] = c; owned_[count_] = true; ++count_;
    return true;
}

bool CodecRegistry::replace(uint8_t pt, ICodec* newCodec) {
    for (size_t i=0;i<count_;++i) {
        if (codecs_[i]->payloadType()==pt) {
            if (owned_[i]) delete codecs_[i];
            codecs_[i]=newCodec; owned_[i]=true;
            return true;
        }
    }
    return false;
}

bool CodecRegistry::remove(uint8_t pt) {
    for (size_t i=0;i<count_;++i) {
        if (codecs_[i]->payloadType()==pt) {
            if (owned_[i]) delete codecs_[i];
            // compact
            for (size_t j=i;j+1<count_;++j) {
                codecs_[j]=codecs_[j+1]; owned_[j]=owned_[j+1];
            }
            --count_; codecs_[count_]=nullptr; owned_[count_]=false;
            return true;
        }
    }
    return false;
}

ICodec* CodecRegistry::findByPT(uint8_t pt) const {
    for (size_t i=0;i<count_;++i) if (codecs_[i]->payloadType()==pt) return codecs_[i];
    return nullptr;
}
ICodec* CodecRegistry::findByName(const char* n) const {
    for (size_t i=0;i<count_;++i)
        if (strcasecmp(codecs_[i]->name(),n)==0) return codecs_[i];
    return nullptr;
}
void CodecRegistry::printAll() const {
    printf("%-20s %4s %8s %5s %8s %8s %s\n",
           "Name","PT","ClkRate","Ch","FrmBytes","FrmSamp","Status");
    for (size_t i=0;i<count_;++i) {
        ICodec* c=codecs_[i];
        // Check if it's a stub (encode returns 0 on dummy call)
        uint8_t dummy_in[4]={};int16_t dummy_out[4]={};
        bool functional = c->decode(dummy_in,c->frameBytes()>4?4:c->frameBytes(),dummy_out,4)!=0
                       || c->payloadType()==101  // telephone-event: special
                       || strcmp(c->name(),"PCMU")==0
                       || strcmp(c->name(),"PCMA")==0
                       || strcmp(c->name(),"L16")==0;
        printf("%-20s %4u %8u %5u %8zu %8zu  %s\n",
               c->name(), c->payloadType(), c->clockRate(), c->channels(),
               c->frameBytes(), c->frameSamples(),
               functional ? "OK" : "STUB (no library)");
    }
}

} // namespace sip
""")

print("All codec files written.")
