// Copyright (c) 2026, Marcin Kwiatkowski <marcin@kwiatkowski.info.pl>
// All rights reserved.

// CodecPlugin.h – Dynamically-attachable codec plugin system
//
// Three attachment methods (all produce ICodec* added to a CodecRegistry):
//
//  1. Compiled-in optional codecs (guarded by HAVE_xxx macros):
//       SLIN  – always available (raw PCM, zero deps)
//       GSM   – libgsm      (HAVE_GSM)
//       G729  – libbcg729   (HAVE_BCG729)
//       C2    – libcodec2   (HAVE_CODEC2)
//
//  2. Shared-library (.so) plugin – C ABI:
//       CodecPlugin::fromSo(path)   dlopen + 8 mandatory symbols
//       See "Plugin C ABI" below for how to write an external plugin.
//
//  3. C++ factory registration:
//       CodecPlugin::fromFactory(name, pt, clockRate, factory)
//       Useful when you have your own C++ ICodec subclass (G.723.1,
//       SILK, MELP, TWELP …) and want it auto-created on demand.
//
// Attach to a CodecRegistry via:
//   CodecPlugin p = CodecPlugin::fromSo("/usr/lib/mycodec.so");
//   if (p) registry.add(p.release());
//
// ── Plugin C ABI ──────────────────────────────────────────────────────────
//
// A shared library codec plugin must export ALL of these C symbols:
//
//   const char* sip_codec_name();          // e.g. "G729" "SILK" "MELP"
//   uint8_t     sip_codec_pt();            // RTP payload type (0..127)
//   uint32_t    sip_codec_clockrate();     // samples/second, e.g. 8000
//   uint8_t     sip_codec_channels();      // 1 (mono) or 2 (stereo)
//   size_t      sip_codec_frame_bytes();   // compressed bytes per frame
//   size_t      sip_codec_frame_samples(); // PCM samples per frame
//   void*       sip_codec_create();        // allocate codec state
//   void        sip_codec_destroy(void*);  // free codec state
//   size_t      sip_codec_encode(void* state,
//                                const int16_t* pcm, size_t samples,
//                                uint8_t* out, size_t outMax);
//   size_t      sip_codec_decode(void* state,
//                                const uint8_t* data, size_t len,
//                                int16_t* pcm, size_t maxSamples);
//
// Build the plugin as a shared library:
//   gcc -shared -fPIC -o mycodec.so mycodec.c -lmycodeclib
//
// A minimal plugin template is generated by:
//   sip_client --codec-template > mycodec_template.c
// ──────────────────────────────────────────────────────────────────────────
#pragma once
#include "Codec.h"
#include <functional>
#include <memory>

namespace sip {

// ── Plugin wrapper returned by factory functions ─────────────────────────────
// Behaves like unique_ptr<ICodec> with a boolean "valid" flag.
/** @brief Owning wrapper around codec instances built from plugin/factory sources. */
class CodecPlugin {
public:
    /** @brief Construct invalid plugin wrapper. */
    CodecPlugin() = default;
    /** @brief Construct wrapper from codec pointer. */
    explicit CodecPlugin(ICodec* c) : codec_(c) {}
    /** @brief Move constructor. */
    CodecPlugin(CodecPlugin&&) = default;
    /** @brief Move assignment. */
    CodecPlugin& operator=(CodecPlugin&&) = default;
    CodecPlugin(const CodecPlugin&) = delete;

    /** @brief True when wrapper owns a valid codec instance. */
    explicit operator bool() const { return codec_ != nullptr; }

    /** @brief Transfer owned codec pointer to caller. */
    ICodec* release() { ICodec* c=codec_; codec_=nullptr; return c; }

    /** @brief Codec name or "(null)" when invalid. */
    const char* name() const { return codec_ ? codec_->name() : "(null)"; }
    /** @brief Codec payload type or 0 when invalid. */
    uint8_t     pt()   const { return codec_ ? codec_->payloadType() : 0; }

    // ── Builders ───────────────────────────────────────────────────────────

    // Load a .so plugin via dlopen.
    // Returns invalid CodecPlugin if the file is missing or ABI incomplete.
    /** @brief Load external codec plugin from shared object path. */
    static CodecPlugin fromSo(const char* soPath);

    // Register a C++ factory function.  The factory is called once now to
    // create the codec instance.  Use this when you have your own ICodec
    // subclass but don't want to write a shared library.
    //   Usage:
    //     auto p = CodecPlugin::fromFactory([]{ return new MySilkCodec(); });
    /** @brief Create codec plugin by invoking C++ factory. */
    static CodecPlugin fromFactory(std::function<ICodec*()> factory);

    // ── Built-in optional codec builders ───────────────────────────────────

    // G.711 PCMU/PCMA (PT 0/8): always available, already in CodecRegistry
    // by default.  Listed for completeness.

    // SLIN – Signed 16-bit Linear PCM, 8 kHz, PT 11 (RFC 3551 "L16/8000/1")
    // No external dependency. Always compiled in.
    /** @brief Build signed-linear PCM codec plugin. */
    static CodecPlugin makeSlin(uint8_t pt = 11);

    // GSM Full-Rate (PT 3). Requires libgsm (-DHAVE_GSM).
    // Returns invalid plugin if not compiled with GSM support.
    /** @brief Build GSM codec plugin when compiled with GSM support. */
    static CodecPlugin makeGsm();

    // G.729A (PT 18). Requires libbcg729 (-DHAVE_BCG729).
    /** @brief Build G.729 codec plugin when compiled with bcg729 support. */
    static CodecPlugin makeG729();

    // CODEC2 (default PT 96). Requires libcodec2 (-DHAVE_CODEC2).
    // mode: 0=3200bps 1=2400bps 2=1600bps 3=1400bps 4=1300bps 5=1200bps
    /** @brief Build CODEC2 codec plugin for selected mode/payload type. */
    static CodecPlugin makeCodec2(int mode = 1, uint8_t pt = 96);

    // G.723.1 (PT 4). No OSS library available on this system.
    // Returns an invalid plugin unless a .so plugin provides it.
    // The stub below always returns silence on decode and silence on encode.
    // Replace by loading a real plugin: fromSo("/usr/lib/g7231codec.so")
    /** @brief Build G.723.1 placeholder codec plugin. */
    static CodecPlugin makeG7231Stub();

    // SILK (PT 97). No OSS library available on this system.
    // Stub only – replace via fromSo() or fromFactory().
    /** @brief Build SILK placeholder codec plugin. */
    static CodecPlugin makeSilkStub(uint8_t pt = 97);

    /**
     * @brief Create MELP 2400bps stub codec plugin (PT 98 by default).
     *
     * Replace with a real implementation via fromSo() or fromFactory().
     */
    static CodecPlugin makeMelpStub(uint8_t pt = 98);

    /**
     * @brief Create MELPe stub codec plugin (PT 99 by default).
     */
    static CodecPlugin makeMelpeStub(uint8_t pt = 99);

    /**
     * @brief Create TWELP stub codec plugin (PT 100 by default).
     *
     * Attach a real implementation via fromSo() or fromFactory().
     */
    static CodecPlugin makeTwelpStub(uint8_t pt = 100);

private:
    ICodec* codec_ = nullptr;
};

// ── Convenience: register all available codecs into a registry ────────────────
// Adds: G711u, G711a, telephone-event (already in default registry),
//       SLIN, GSM (if HAVE_GSM), G.729 (if HAVE_BCG729),
//       CODEC2-2400 (if HAVE_CODEC2), and stubs for the rest.
// Dynamic PTs for stubs: C2=96 SILK=97 MELP=98 MELPe=99 TWELP=100
void registerAllCodecs(CodecRegistry& reg,
                       bool includeStubs = true);

// Print a plugin template to stdout (for writing new plugins).
void printCodecPluginTemplate();

} // namespace sip
